apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 578673726898.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:63a2edd201eb5b84f7d1eeb84dbccc328cb6713b
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: electronics-service
  labels:
    app: electronics
spec:
  type: ClusterIP
  selector:
    app: electronics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
