apiVersion: apps/v1
kind: Deployment
metadata:
  name: beauty-deployment
  labels:
    app: beauty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beauty
  template:
    metadata:
      labels:
        app: beauty
    spec:
      containers:
      - name: beauty
        image: 578673726898.dkr.ecr.us-east-1.amazonaws.com/shopping-site-beauty:a206a55047f0fcf7022b2a386116d38b6e6331ea
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: beauty-service
  labels:
    app: beauty
spec:
  type: ClusterIP
  selector:
    app: beauty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
