apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deployment
  labels:
    app: auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto
  template:
    metadata:
      labels:
        app: auto
    spec:
      containers:
      - name: auto
        image: 578673726898.dkr.ecr.us-east-1.amazonaws.com/shopping-site-auto:a206a55047f0fcf7022b2a386116d38b6e6331ea
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auto-service
  labels:
    app: auto
spec:
  type: ClusterIP
  selector:
    app: auto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
